version: '3.6'

services:
    laravel-skeleton:
        tty: true
        image: lorisleiva/laravel-docker:7.4
        environment:
            - DB_HOST=mysql
            - DB_USERNAME=root
            - DB_DATABASE=laravel-skeleton
            - DB_PASSWORD=secret
        command: 'php artisan serve --port=5000 --host=0.0.0.0'
        ports:
            - 5000:5000
        volumes:
            - ./:/var/www
    mysql:
        image: 'mysql:5.7.21'
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=laravel-skeleton
        ports:
            - 33065:3306
